blank_issues_enabled: true
contact_links:
  - name: 💬 Discussions
    url: https://github.com/ooples/token-optimizer-mcp/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/ooples/token-optimizer-mcp#readme
    about: Read the documentation
  - name: 🔒 Security Issue
    url: https://github.com/ooples/token-optimizer-mcp/security/advisories/new
    about: Report a security vulnerability privately
