/**
 * Where the file tools put the pre-write copy of a file.
 *
 * Lives in utils because smart_edit and smart_write both make backups, and the
 * fix below was applied to smart_edit only -- so smart_write went on writing
 * `<file>.bak` into the user's repository long after the defect was understood.
 * Measured on this checkout: three stray .bak files, including one beside a
 * test fixture and one beside a hook that is regenerated by a sync script.
 *
 * The backup used to be written NEXT TO THE ORIGINAL. That leaves an untracked
 * `README.md.bak` in `git status`, one `git add -A` from being committed, and
 * nothing ever deletes it. A safety net that dirties the tree it is protecting
 * is a poor trade.
 *
 * Backups now live under the user's home directory, keyed by a hash of the
 * absolute path so two files sharing a basename cannot collide, and capped so
 * they cannot grow without bound.
 */

import { mkdirSync, writeFileSync, readdirSync, unlinkSync } from 'fs';
import { join, basename } from 'path';
import { homedir } from 'os';
import { createHash } from 'crypto';

/** Outside every working tree, so a backup can never be committed. */
export const BACKUP_ROOT = join(homedir(), '.token-optimizer', 'backups');

/** How many past versions of one file are kept before the oldest is dropped. */
const BACKUPS_PER_FILE = 5;

/**
 * Saves content somewhere it cannot do harm.
 *
 * Failure is never allowed to fail the operation -- the backup is a
 * convenience, the write is the job. But the RETURN VALUE is the outcome, not
 * the request: callers used to report `wasBackedUp` from the caller's own
 * option, so a full disk or a read-only home directory produced a result
 * claiming a backup that was never written. That is precisely the moment
 * somebody relies on it.
 *
 * @returns true only if a backup file is actually on disk.
 */
export function writeBackup(
  filePath: string,
  content: string,
  encoding: BufferEncoding = 'utf-8'
): boolean {
  try {
    const key = createHash('sha256')
      .update(filePath)
      .digest('hex')
      .slice(0, 16);
    const dir = join(BACKUP_ROOT, key);
    mkdirSync(dir, { recursive: true });

    const stamp = new Date().toISOString().replace(/[:.]/g, '-');
    writeFileSync(
      join(dir, `${stamp}__${basename(filePath)}`),
      content,
      encoding
    );

    const existing = readdirSync(dir).sort();
    for (const stale of existing.slice(
      0,
      Math.max(0, existing.length - BACKUPS_PER_FILE)
    )) {
      try {
        unlinkSync(join(dir, stale));
      } catch {
        // A backup we cannot prune is not worth failing a write over.
      }
    }

    return true;
  } catch {
    return false;
  }
}
