/**
 * Where the file tools put the pre-write copy of a file.
 *
 * Lives in utils because smart_edit and smart_write both make backups, and the
 * fix below was applied to smart_edit only -- so smart_write went on writing
 * `<file>.bak` into the user's repository long after the defect was understood.
 * Measured on this checkout: three stray .bak files, including one beside a
 * test fixture and one beside a hook that is regenerated by a sync script.
 *
 * The backup used to be written NEXT TO THE ORIGINAL. That leaves an untracked
 * `README.md.bak` in `git status`, one `git add -A` from being committed, and
 * nothing ever deletes it. A safety net that dirties the tree it is protecting
 * is a poor trade.
 *
 * Backups now live under the user's home directory, keyed by a hash of the
 * absolute path so two files sharing a basename cannot collide, and capped so
 * they cannot grow without bound.
 */

import { mkdirSync, writeFileSync, readdirSync, unlinkSync } from 'fs';
import { join, basename } from 'path';
import { homedir } from 'os';
import { createHash, randomBytes } from 'crypto';

/**
 * Overrides the backup location.
 *
 * Without it the root is a fixed constant, so every test that exercises
 * `writeBackup` writes into the developer's or CI runner's REAL home directory
 * and has to remember to clean up by hand. One test forgot, and each run left a
 * permanent directory behind -- the same category of defect (a backup landing
 * where it should not) that this module exists to fix.
 */
const BACKUP_DIR_ENV = 'TOKEN_OPTIMIZER_BACKUP_DIR';

/** Default root: outside every working tree, so a backup can never be committed. */
export const BACKUP_ROOT = join(homedir(), '.token-optimizer', 'backups');

/**
 * The root to write to right now.
 *
 * Read per call rather than captured at import, so a test can redirect it after
 * this module has already been loaded.
 */
export function backupRoot(): string {
  return process.env[BACKUP_DIR_ENV] || BACKUP_ROOT;
}

/** The directory holding one file's backups. Exported so tests can assert on it. */
export function backupDirFor(filePath: string): string {
  const key = createHash('sha256').update(filePath).digest('hex').slice(0, 16);
  return join(backupRoot(), key);
}

/** How many past versions of one file are kept before the oldest is dropped. */
const BACKUPS_PER_FILE = 5;

/** Monotonic within this process, so two calls in one millisecond still differ. */
let sequence = 0;

/**
 * Saves content somewhere it cannot do harm.
 *
 * Failure is never allowed to fail the operation -- the backup is a
 * convenience, the write is the job. But the RETURN VALUE is the outcome, not
 * the request: callers used to report `wasBackedUp` from the caller's own
 * option, so a full disk or a read-only home directory produced a result
 * claiming a backup that was never written. That is precisely the moment
 * somebody relies on it.
 *
 * @returns true only if a backup file is actually on disk.
 */
export function writeBackup(
  filePath: string,
  content: string,
  encoding: BufferEncoding = 'utf-8'
): boolean {
  try {
    const dir = backupDirFor(filePath);
    mkdirSync(dir, { recursive: true });

    // NOT the timestamp alone. `toISOString()` has millisecond resolution, and
    // one call takes ~1.09 ms, so sequential calls only just miss each other --
    // but concurrent ones do not. Measured: five concurrent backups of one file
    // produced four files, silently losing a version.
    //
    // The sequence keeps callers in THIS process apart; the random suffix keeps
    // separate processes apart. The timestamp stays first so the lexical sort
    // used for pruning still orders by age.
    const stamp = new Date().toISOString().replace(/[:.]/g, '-');
    const unique = `${String(sequence++).padStart(4, '0')}-${randomBytes(3).toString('hex')}`;
    writeFileSync(
      join(dir, `${stamp}__${unique}__${basename(filePath)}`),
      content,
      encoding
    );

    const existing = readdirSync(dir).sort();
    for (const stale of existing.slice(
      0,
      Math.max(0, existing.length - BACKUPS_PER_FILE)
    )) {
      try {
        unlinkSync(join(dir, stale));
      } catch {
        // A backup we cannot prune is not worth failing a write over.
      }
    }

    return true;
  } catch {
    return false;
  }
}
