/**
 * Regenerate the pinned corpus the code workloads are built from.
 *
 * THE POINT OF THE FILE THIS WRITES is that it does not change unless someone
 * runs this script. Walking the repository at bench time made two fixtures
 * move with ordinary source commits -- 44b28702 added ~2 KB to
 * src/core/cache-engine.ts and silently moved codebase-exploration by 2,088
 * canonical characters and repeated-reads by 6,264, with no benchmark change
 * at all. A figure that moves for that reason cannot be ratcheted and cannot
 * be reproduced from another checkout.
 *
 * Run this only when the corpus is MEANT to change, and expect the diff to be
 * reviewed: it invalidates payloadsDigest on every code workload, so every
 * recorded figure derived from them has to be re-recorded afterwards.
 *
 *   node bench/compression/snapshot-corpus.mjs
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  CORPUS_SPEC,
  REPO,
  realSourcesLive,
  searchResultsLive,
  sourcesKey,
  searchKey,
} from './fixtures.mjs';

const OUT = fileURLToPath(new URL('./corpus.snapshot.json', import.meta.url));

const entries = {};
for (const item of CORPUS_SPEC) {
  const root = join(REPO, ...item.root);
  if (item.kind === 'sources') {
    const key = sourcesKey(root, item.budget);
    entries[key] = realSourcesLive(root, item.budget);
  } else {
    const key = searchKey(root, item.pattern, item.budget);
    entries[key] = searchResultsLive(root, item.pattern, item.budget);
  }
}

// A WALK THAT COMES BACK EMPTY IS A BROKEN SNAPSHOT, NOT AN EMPTY CORPUS, and
// writing it would hand every code workload a near-zero payload that still
// looks like a valid recording.
for (const [key, text] of Object.entries(entries)) {
  if (typeof text !== 'string' || text.length === 0)
    throw new Error(`corpus walk produced nothing for ${key}`);
}

const payload = {
  note:
    'Generated by bench/compression/snapshot-corpus.mjs. Do not hand-edit: ' +
    'these bytes pin what the code workloads measure, and changing them ' +
    'invalidates payloadsDigest on every row built from them.',
  entries,
};

writeFileSync(OUT, `${JSON.stringify(payload, null, 2)}\n`, 'utf8');

for (const [key, text] of Object.entries(entries))
  console.log(`  ${key}  ${text.length} chars`);
console.log(`wrote ${OUT}`);
